### PR TITLE
Created directory selection view

### LINKED ISSUE #27: Implement project's directory choice view
## Description
Refer to this part:
image

## Correct issue checklist:
- [x] I have added a detailed description
- [x] I have assigned a Team label (front-end / node / git / design / gatsby)
- [x] I have assigned a Description label (enhancement / bug / etc.)
- [x] I have assigned a Project

### PR DESCRIPTION
**Pull request by 217868**
## Linked issues
closes #27 

## Correct PR Checklist
- [x] I have linked an issue (use e.g. `closes #1`)
- [x] I have assigned Reviewers
- [x] I have assigned a Team label
- [x] I have assigned an Description label
- [x] I have assigned a Project
- [ ] I have assigend a Milestone

### CODE REVIEW

**Comment by lukasz-starosta** [comment]
Remember to format this with .prettierrc, you can run `yarn prettier --write --config .prettierrc ./src` when in project root directory, that should do the job

**Comment by karczewskiPiotr** [comment]
> Remember to format this with .prettierrc, you can run `yarn prettier --write --config .prettierrc ./src` when in project root directory, that should do the job

There's a script in the project for simplicity so you can just run `yarn format`.

**Review by lukasz-starosta — APPROVED** [review]
I think it's fine, just format it so CI passes

**Review by lukasz-starosta — APPROVED** [review]

**Review by 217853 — APPROVED** [review]

**Review by Eleara — APPROVED** [review]

**Comment by karczewskiPiotr** [comment]
@217868 Not entirely sure but it seems like this may not be in the correct place of the app and in the wrong order of the app's lifecycle. I think it maybe doesn't do exactly what design team intended? From wireframes it looks like it's just a one time thing on the first log in but then again kind of loops. Maybe could convert this to WIP and consult the design team before merging?

**Comment by 217868** [comment]
> @217868 Not entirely sure but it seems like this may not be in the correct place of the app and in the wrong order of the app's lifecycle. I think it maybe doesn't do exactly what design team intended? From wireframes it looks like it's just a one time thing on the first log in but then again kind of loops. Maybe could convert this to WIP and consult the design team before merging?

I propose to merge it for now and modify this solution to being dependend on app settings after they are implemented. Then, we can display that screen only if these settings are absent in the app.

**Pull request closed without merging**
